package com.example.pantaujompo.core.util

object AppStrings {
    fun get(key: String, language: String): String {
        return if (language == "en") {
            enStrings[key] ?: key
        } else {
            idStrings[key] ?: key
        }
    }

    private val idStrings = mapOf(
        "beranda" to "Beranda",
        "nutrisi" to "Nutrisi",
        "statistik" to "Statistik",
        "artikel" to "Artikel",
        "profil" to "Profil",
        "selamat_pagi" to "Selamat Pagi",
        "selamat_siang" to "Selamat Siang",
        "selamat_sore" to "Selamat Sore",
        "selamat_malam" to "Selamat Malam",
        "pengguna" to "Pengguna",
        "total_minggu_ini" to "Total Minggu Ini",
        "total_jarak" to "Total Jarak",
        "kalori" to "Kalori",
        "durasi" to "Durasi",
        "mulai_aktivitas" to "Mulai Aktivitas",
        "aktivitas_hari_ini" to "Aktivitas Hari Ini",
        "lihat_semua" to "Lihat Semua",
        "kalori_aktif" to "Kalori Aktif",
        "jarak_tempuh" to "Jarak Tempuh",
        "nutrisi_harian" to "Nutrisi Harian (Cek Menu Pemindai)",
        "karbo" to "Karbo",
        "protein" to "Protein",
        "lemak" to "Lemak",
        "saran_ai" to "Saran Gaya Hidup Sehat AI",
        "pilih_jenis_aktivitas" to "Pilih Jenis Aktivitas",
        "pantau_aktivitas" to "Pantau aktivitas yang sesuai dengan kebutuhanmu hari ini.",
        "jalan_santai" to "Jalan Santai",
        "lari_jogging" to "Lari / Jogging",
        "bersepeda" to "Bersepeda",
        "cocok_pemulihan" to "Cocok untuk pemulihan dan kesehatan sendi",
        "bakar_kalori" to "Bakar kalori dan tingkatkan kardio",
        "latihan_minim_benturan" to "Latihan minim benturan yang menyenangkan",
        "pengaturan" to "Pengaturan",
        "sesuaikan_preferensi" to "Sesuaikan preferensimu",
        "tampilan" to "TAMPILAN",
        "mode_gelap" to "Mode Gelap",
        "gelap_aktif" to "Aktif - Tampilan gelap premium",
        "gelap_nonaktif" to "Nonaktif - Tampilan terang bersih",
        "teks_besar" to "Teks Besar",
        "teks_aktif" to "Aktif - Font diperbesar 20%",
        "teks_nonaktif" to "Nonaktif - Ukuran normal",
        "bahasa_satuan" to "BAHASA & SATUAN",
        "bahasa_inggris" to "Bahasa Inggris",
        "bahasa_aktif" to "Bahasa Indonesia (Aktif)",
        "privasi_keamanan" to "PRIVASI & KEAMANAN",
        "hapus_data" to "Hapus Semua Data",
        "hapus_data_desc" to "Ini akan menghapus seluruh riwayat olahraga dan nutrisi",
        "kebijakan_privasi" to "Kebijakan Privasi",
        "kebijakan_desc" to "Lihat bagaimana data kamu digunakan",
        "tentang_aplikasi" to "TENTANG APLIKASI",
        "tentang_pantau" to "Tentang Pantau Jompo",
        "dibuat_dengan" to "Dibuat dengan ❤️",
        "deskripsi_app" to "Aplikasi monitoring kesehatan dan kebugaran untuk lansia. Dilengkapi dengan tracking olahraga berbasis GPS, analisis nutrisi menggunakan AI, dan pemantauan kondisi fisik secara komprehensif.",
        "hapus_semua_tanya" to "Hapus Semua Data?",
        "hapus_semua_peringatan" to "Semua riwayat olahraga, nutrisi, dan pengaturan profil akan dihapus permanen. Tindakan ini tidak bisa dibatalkan.",
        "hapus_semuanya" to "Hapus Semuanya",
        "batal" to "Batal",
        "hari_ini_tgl" to "Hari ini, ",
        "kalori_hari_ini" to "Kalori Hari Ini",
        "belum_ada_asupan" to "Belum ada asupan makanan hari ini",
        "tap_kamera" to "Tap tombol kamera di atas untuk mulai!",
        "set_target_kalori" to "Set Target Kalori",
        "contoh_kalori" to "Contoh: 2000",
        "simpan" to "Simpan",
        "detail_makanan" to "Detail Makanan",
        "insight_ai" to "💡 Insight AI:",
        "cek_kalori_makanan" to "Cek Kalori Makanan",
        "gunakan_kamera_ketik" to "Gunakan kamera atau ketik nama",
        "asupan_hari_ini" to "Asupan Hari Ini",
        "makanan" to "makanan",
        "item" to "item",
        "ai_nutrition_scanner" to "AI Nutrition Scanner",
        "foto_atau_ketik" to "Foto atau ketik nama makanan",
        "kamera" to "Kamera",
        "galeri" to "Galeri",
        "atau_ketik" to "Atau ketik: Nasi goreng, Apel...",
        "menganalisis" to "Menganalisis...",
        "analisis_dengan_ai" to "ANALISIS DENGAN AI",
        "simpan_ke_riwayat" to "SIMPAN KE RIWAYAT",
        "tidak_terdeteksi" to "Tidak Terdeteksi",
        "gagal_analisis" to "Gagal menganalisis. Coba lagi.",
        "ganti_foto_profil" to "Ganti Foto Profil",
        "nama_pengguna" to "Nama Pengguna",
        "data_biometrik" to "DATA BIOMETRIK",
        "usia" to "Usia",
        "berat" to "Berat",
        "tinggi" to "Tinggi",
        "indeks_massa_tubuh" to "INDEKS MASSA TUBUH",
        "belum_diisi" to "BELUM DIISI",
        "kurus" to "KURUS",
        "ideal" to "IDEAL",
        "overweight" to "OVERWEIGHT",
        "obesitas" to "OBESITAS",
        "simpan_profil" to "SIMPAN PROFIL",
        "buka_kamera" to "Buka Kamera",
        "preview_saja" to "Preview saja (tidak tersimpan permanen)",
        "pilih_dari_galeri" to "Pilih dari Galeri",
        "tersimpan_permanen" to "Tersimpan permanen di aplikasi",
        "total_waktu" to "Total Waktu",
        "th" to "th",
        "kg" to "kg",
        "cm" to "cm",
        "quote_1" to "Umur hanyalah angka. Tetap aktif, sehat, dan bahagia di usia senja bersama Pantau Jompo! ✨",
        "quote_2" to "Kesehatan adalah investasi terbaik untuk masa depan. Mari mulai hari ini! \uD83C\uDFC3\u200D♂\uFE0F",
        "quote_3" to "Bergerak selagi bisa, bernutrisi selagi mampu. 🌟",
        "quote_4" to "Nutrisi seimbang dan langkah konsisten adalah rahasia jiwa muda. 🥗",
        "quote_5" to "Hari ini adalah kesempatan baru untuk versi dirimu yang lebih sehat. 💪",
        "quote_6" to "Kesehatan adalah mahkota di kepala orang sehat yang hanya bisa dilihat oleh orang sakit. ✨",
        "ai_assistant" to "AI Assistant",
        "gaya_hidup_sehat" to "Gaya Hidup Sehat",
        "ai_sedang_mengetik" to "AI sedang mengetik...",
        "tanya_kesehatan" to "Tanya seputar kesehatan...",
        "halo_ai" to "Halo! Saya Asisten AI Pantau Jompo 🤖\n\nAda yang bisa saya bantu seputar kesehatan, nutrisi, atau olahraga hari ini?",
        "tracking_lari" to "Tracking Lari",
        "tracking_jalan" to "Tracking Jalan",
        "tracking_sepeda" to "Tracking Sepeda",
        "waktu" to "Waktu",
        "pace" to "Pace",
        "mulai" to "Mulai",
        "jeda" to "Jeda",
        "lanjutkan" to "Lanjutkan",
        "selesai" to "Selesai",
        "kembali" to "Kembali",
        "riwayat_olahraga" to "Riwayat Olahraga",
        "minggu_ini" to "Minggu Ini",
        "total_sesi" to "Total Sesi",
        "detail_aktivitas" to "Detail Aktivitas",
        "peta_rute" to "Peta Rute",
        "waktu_mulai" to "Waktu Mulai",
        "gps_aktif" to "GPS Aktif",
        "gps_terputus" to "GPS Terputus",
        "filter_harian" to "Hari Ini",
        "filter_mingguan" to "Minggu Ini",
        "filter_bulanan" to "Bulan Ini",
        "filter_semua" to "Semua",
        "mulai_setup_profil" to "Mulai / Setup Profil",
        "selanjutnya" to "Selanjutnya",
        "apa_itu_pantau_jompo" to "Apaan sih ini bray?",
        "apa_itu_pantau_jompo_desc" to "Tenang bray, ini BUKAN aplikasi buat lansia beneran! Tapi buat kita-kita anak muda (terutama kaum jompo pra-sejahtera) yang baru naik tangga 3 anak udah ngos-ngosan, pinggang langsung encok pas nonton konser, dan kalo bersin berpotensi besar mengalami salah urat.\n\nAplikasi ini siap memantau kebugaran darurat kamu dengan bantuan AI Scanner dan GPS tracker, biar kamu ga jompo-jompo amat sebelum waktunya! Tetap sehat bray, perjalanan hidup kita masih panjang dan berliku! \uD83D\uDE80✨",
        "teknologi_di_balik_layar" to "Teknologi Di Balik Layar",
        "tim_pengembang" to "Tim Pengembang (Kaum Jompo)",
        "pengembang_kelas_rb" to "Pengembang Aplikasi Mobile Kelas RB",
        "sedang_berjalan" to "Sedang Berjalan",
        "siap_pecahkan_rekor" to "Siap pecahkan rekor hari ini? Gas!",
        "onboarding_1_title" to "Mulai Bergerak dan Energik",
        "onboarding_1_desc" to "Waktunya bangun dan penuhi targetmu! Pantau rute, langkah, dan energimu setiap hari tanpa ribet.",
        "onboarding_2_title" to "Sehat Itu Mudah & Nyaman",
        "onboarding_2_desc" to "Makan enak tetap terkontrol. Pindai makananmu dengan AI yang super friendly dan otomatis menghitung gizimu.",
        "onboarding_3_title" to "Masa Depan Fitnesmu",
        "onboarding_3_desc" to "Mari buat profil untuk AI kami. Dapatkan rekomendasi yang dibuat eksklusif hanya untuk dirimu.",
        "pilih_kamera_galeri" to "Pilih Kamera atau Galeri"
    )

    private val enStrings = mapOf(
        "beranda" to "Home",
        "nutrisi" to "Nutrition",
        "statistik" to "Statistics",
        "artikel" to "Articles",
        "profil" to "Profile",
        "selamat_pagi" to "Good Morning",
        "selamat_siang" to "Good Afternoon",
        "selamat_sore" to "Good Evening",
        "selamat_malam" to "Good Night",
        "pengguna" to "User",
        "total_minggu_ini" to "Total This Week",
        "total_jarak" to "Total Distance",
        "kalori" to "Calories",
        "durasi" to "Duration",
        "mulai_aktivitas" to "Start Activity",
        "aktivitas_hari_ini" to "Today's Activity",
        "lihat_semua" to "See All",
        "kalori_aktif" to "Active Calories",
        "jarak_tempuh" to "Distance",
        "nutrisi_harian" to "Daily Nutrition (Check Scanner Menu)",
        "karbo" to "Carbs",
        "protein" to "Protein",
        "lemak" to "Fat",
        "saran_ai" to "AI Healthy Lifestyle Suggestion",
        "pilih_jenis_aktivitas" to "Choose Activity Type",
        "pantau_aktivitas" to "Track activity that fits your needs today.",
        "jalan_santai" to "Walking",
        "lari_jogging" to "Running / Jogging",
        "bersepeda" to "Cycling",
        "cocok_pemulihan" to "Great for recovery and joint health",
        "bakar_kalori" to "Burn calories and improve cardio",
        "latihan_minim_benturan" to "Fun low-impact exercise",
        "pengaturan" to "Settings",
        "sesuaikan_preferensi" to "Customize your preferences",
        "tampilan" to "APPEARANCE",
        "mode_gelap" to "Dark Mode",
        "gelap_aktif" to "Active - Premium dark theme",
        "gelap_nonaktif" to "Inactive - Clean light theme",
        "teks_besar" to "Large Text",
        "teks_aktif" to "Active - Font enlarged 20%",
        "teks_nonaktif" to "Inactive - Normal size",
        "bahasa_satuan" to "LANGUAGE & UNITS",
        "bahasa_inggris" to "Switch to Bahasa",
        "bahasa_aktif" to "English (Active)",
        "privasi_keamanan" to "PRIVACY & SECURITY",
        "hapus_data" to "Clear All Data",
        "hapus_data_desc" to "This will delete all history",
        "kebijakan_privasi" to "Privacy Policy",
        "kebijakan_desc" to "See how your data is used",
        "tentang_aplikasi" to "ABOUT APP",
        "tentang_pantau" to "About Pantau Jompo",
        "dibuat_dengan" to "Made with ❤️",
        "deskripsi_app" to "Health and fitness monitoring app for seniors. Features GPS-based workout tracking, AI nutrition analysis, and comprehensive physical monitoring.",
        "hapus_semua_tanya" to "Clear All Data?",
        "hapus_semua_peringatan" to "All workout history, nutrition logs, and profile settings will be permanently deleted. This action cannot be undone.",
        "hapus_semuanya" to "Delete Everything",
        "batal" to "Cancel",
        "hari_ini_tgl" to "Today, ",
        "kalori_hari_ini" to "Today's Calories",
        "belum_ada_asupan" to "No food intake today yet",
        "tap_kamera" to "Tap the camera button above to start!",
        "set_target_kalori" to "Set Calorie Target",
        "contoh_kalori" to "Example: 2000",
        "simpan" to "Save",
        "detail_makanan" to "Food Detail",
        "insight_ai" to "💡 AI Insight:",
        "cek_kalori_makanan" to "Check Food Calories",
        "gunakan_kamera_ketik" to "Use camera or type name",
        "asupan_hari_ini" to "Today's Intake",
        "makanan" to "food",
        "item" to "item",
        "ai_nutrition_scanner" to "AI Nutrition Scanner",
        "foto_atau_ketik" to "Take a photo or type food name",
        "kamera" to "Camera",
        "galeri" to "Gallery",
        "atau_ketik" to "Or type: Fried rice, Apple...",
        "menganalisis" to "Analyzing...",
        "analisis_dengan_ai" to "ANALYZE WITH AI",
        "simpan_ke_riwayat" to "SAVE TO HISTORY",
        "tidak_terdeteksi" to "Not Detected",
        "gagal_analisis" to "Failed to analyze. Try again.",
        "ganti_foto_profil" to "Change Profile Picture",
        "nama_pengguna" to "Username",
        "data_biometrik" to "BIOMETRIC DATA",
        "usia" to "Age",
        "berat" to "Weight",
        "tinggi" to "Height",
        "indeks_massa_tubuh" to "BODY MASS INDEX",
        "belum_diisi" to "NOT SET",
        "kurus" to "UNDERWEIGHT",
        "ideal" to "IDEAL",
        "overweight" to "OVERWEIGHT",
        "obesitas" to "OBESE",
        "simpan_profil" to "SAVE PROFILE",
        "buka_kamera" to "Open Camera",
        "preview_saja" to "Preview only (not saved permanently)",
        "pilih_dari_galeri" to "Choose from Gallery",
        "tersimpan_permanen" to "Saved permanently in app",
        "total_waktu" to "Total Time",
        "th" to "yo",
        "kg" to "kg",
        "cm" to "cm",
        "quote_1" to "Age is just a number. Stay active, healthy, and happy in your golden years with Pantau Jompo! ✨",
        "quote_2" to "Health is the best investment for the future. Let's start today! 🏃‍♂️",
        "quote_3" to "Move while you can, nourish while you're able. 🌟",
        "quote_4" to "Balanced nutrition and consistent steps are the secret to a youthful soul. 🥗",
        "quote_5" to "Today is a new opportunity for a healthier version of you. 💪",
        "quote_6" to "Health is a crown on the healthy person's head that only the sick person can see. ✨",
        "ai_assistant" to "AI Assistant",
        "gaya_hidup_sehat" to "Healthy Lifestyle",
        "ai_sedang_mengetik" to "AI is typing...",
        "tanya_kesehatan" to "Ask about health...",
        "halo_ai" to "Hello! I am Pantau Jompo AI Assistant 🤖\n\nIs there anything I can help with regarding health, nutrition, or exercise today?",
        "tracking_lari" to "Run Tracking",
        "tracking_jalan" to "Walk Tracking",
        "tracking_sepeda" to "Cycling Tracking",
        "waktu" to "Time",
        "pace" to "Pace",
        "mulai" to "Start",
        "jeda" to "Pause",
        "lanjutkan" to "Resume",
        "selesai" to "Finish",
        "kembali" to "Back",
        "riwayat_olahraga" to "Exercise History",
        "minggu_ini" to "This Week",
        "total_sesi" to "Total Sessions",
        "detail_aktivitas" to "Activity Detail",
        "peta_rute" to "Route Map",
        "waktu_mulai" to "Start Time",
        "gps_aktif" to "GPS Active",
        "gps_terputus" to "GPS Disconnected",
        "filter_harian" to "Today",
        "filter_mingguan" to "This Week",
        "filter_bulanan" to "This Month",
        "filter_semua" to "All",
        "mulai_setup_profil" to "Start / Setup Profile",
        "selanjutnya" to "Next",
        "apa_itu_pantau_jompo" to "What is this bro?",
        "apa_itu_pantau_jompo_desc" to "Relax bro, this is NOT a real app for the elderly! But for us young people (especially the frail youth) who pant after 3 stairs, get back pain at concerts, and risk spraining a muscle when sneezing.\n\nThis app is ready to monitor your emergency fitness with AI Scanner and GPS tracker, so you don't get too frail before your time! Stay healthy bro, our life journey is still long and winding! \uD83D\uDE80✨",
        "teknologi_di_balik_layar" to "Technology Behind The Scenes",
        "tim_pengembang" to "Development Team (The Frail Youth)",
        "pengembang_kelas_rb" to "Mobile App Dev Class RB",
        "sedang_berjalan" to "Running Now",
        "siap_pecahkan_rekor" to "Ready to break records today? Go!",
        "onboarding_1_title" to "Start Moving and Be Energetic",
        "onboarding_1_desc" to "Time to wake up and meet your targets! Track routes, steps, and energy every day effortlessly.",
        "onboarding_2_title" to "Healthy is Easy & Comfort",
        "onboarding_2_desc" to "Eat well and stay controlled. Scan your food with super friendly AI that automatically calculates nutrition.",
        "onboarding_3_title" to "Your Fitness Future",
        "onboarding_3_desc" to "Let's create a profile for our AI. Get exclusive recommendations just for you.",
        "pilih_kamera_galeri" to "Choose Camera or Gallery"
    )
}
