# Gradle Properties
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Kotlin
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.dependency.excludeLibraryComponentsFromConstraints=true

# Temporary bypass for AGP 9.x + KMP compatibility
android.builtInKotlin=false
android.newDsl=false
