package com.example.bridgebit.domain.model

/**
 * Domain model representing a single quiz question generated by AI.
 *
 * This is the canonical model used across the Presentation and Domain layers.
 * The Data layer maps [com.example.bridgebit.data.remote.dto.QuizQuestionDto]
 * to this class before passing it up the chain.
 *
 * @param question   The quiz question text displayed to the user.
 * @param options    Exactly 4 multiple-choice answer options (A–D).
 * @param correctOptionIndex Zero-based index (0=A, 1=B, 2=C, 3=D) of the correct answer.
 * @param explanation A brief explanation shown after the user answers.
 */
data class QuizQuestion(
    val question: String,
    val options: List<String>,
    val correctOptionIndex: Int,
    val explanation: String
)
