package com.example.neurodeck.domain.model

import kotlinx.datetime.Clock
import kotlinx.datetime.Instant

/**
 * Deck = kumpulan flashcard yang related satu topik.
 *
 * Contoh: "Kalkulus UAS", "Bahasa Inggris TOEFL", "Pemrograman Mobile".
 *
 * Catatan: [cardCount] tidak persistent di tabel `decks` — di-compute via JOIN
 * dengan tabel `cards`. Tapi karena UI butuh angka ini di Deck Library,
 * domain model bawa field-nya.
 */
data class Deck(
    /** Auto-generated by SQLDelight. 0 untuk deck baru yang belum di-persist. */
    val id: Long = 0,

    /** Nama deck, e.g. "Kalkulus Bab 3". Wajib non-empty (validation di ViewModel). */
    val title: String,

    /** Deskripsi opsional, e.g. "Materi turunan dan integral". */
    val description: String = "",

    /** Jumlah kartu di deck ini. Computed via JOIN, tidak di-set saat insert. */
    val cardCount: Int = 0,

    val createdAt: Instant = Clock.System.now(),
    val updatedAt: Instant = Clock.System.now(),
)