package com.example.inventra.core.localization

object EnglishStrings : Strings {
    override val appName = "InventRa"
    override val catalog = "Catalog"
    override val history = "History"
    override val profile = "Profile"
    override val aiAssistant = "AI Assistant"
    override val home = "Home"
    
    // Dashboard
    override val dashboardOverview = "Dashboard Overview"
    override val dashboardSubtitle = "Manage your assets and tracking efficiently."
    override val totalItems = "TOTAL ITEMS"
    override val borrowed = "BORROWED"
    override val available = "AVAILABLE"
    override val activeBorrowing = "Active Borrowing"
    override val registerNewItem = "Register New Item"
    override val registerNewItemDesc = "Quickly add new stock into the inventory database."
    override val getStarted = "Get Started"
    override val borrower = "Borrower"
    override val dueDate = "Due date"
    override val overdueAlert = "borrowing overdue!"
    override val takeAction = "Take action immediately."
    override val failedToLoadData = "Failed to load data"
    
    // Profile Screen
    override val myProfile = "My Profile"
    override val editProfile = "Edit Profile"
    override val fullName = "Division"
    override val phoneNumber = "Phone Number"
    override val cancel = "Cancel"
    override val save = "Save"
    override val darkMode = "Dark Mode"
    override val accountManagement = "Account Management"
    override val resetAllData = "Reset All Data"
    override val logout = "Logout Account"
    override val language = "Language"
    override val changeLanguage = "Change Language"
    override val confirmResetTitle = "Reset All Data"
    override val confirmResetMessage = "Are you sure you want to delete all items & borrowing history? This cannot be undone."
    
    // History / Borrowing
    override val borrowing = "Borrowing"
    override val pending = "Pending"
    override val active = "Active"
    override val all = "All"
    override val returned = "RETURNED"
    override val overdue = "OVERDUE"
    override val waitingApproval = "WAITING"
    override val approveBorrow = "Approve Borrow"
    override val approveReturn = "Confirm Return"
    override val returnItem = "Return Item"
    override val returnDate = "Return Date"
    override val fine = "Fine"
    override val noHistoryTitle = "No History Yet"
    override val noHistoryDesc = "No borrowing transactions recorded yet."
    override val noPendingTitle = "No Data"
    override val noPendingDesc = "No pending requests at this time."
    override val noActiveTitle = "No Data"
    override val noActiveDesc = "No active borrowings at this time."
    override val pendingActionDesc = "requests/returns waiting for Admin approval."
    
    // Items & Detail
    override val itemName = "Item Name"
    override val description = "Description"
    override val location = "Location"
    override val totalStock = "Total Stock"
    override val availableStock = "Available"
    override val category = "Category"
    override val condition = "Condition"
    override val pic = "Person In Charge"
    override val picPhone = "PIC Phone Number"
    override val itemInformation = "Item Information"
    override val loanPolicy = "Loan Policy"
    override val maxDuration = "Max Duration"
    override val overdueFine = "Overdue Fine"
    override val admin = "Admin"
    override val itemNotFound = "Item not found"
    override val contactPIC = "Contact PIC"
    override val borrow = "Borrow"
    override val outOfStock = "Out of Stock"
    override val deleteItem = "Delete Item"
    override val deleteItemConfirm = "Are you sure you want to delete this item? This action cannot be undone."
    override val requestBorrow = "Request Borrowing"
    override val requestBorrowDesc = "Request will be processed by Admin."
    override val borrowerNameLabel = "Division Head Name *"
    override val submitRequest = "Submit"
    override val requestSent = "✅ Borrowing request sent! Wait for admin confirmation."
    override val locationNotSet = "Location not set"

    // Item Conditions
    override val condNew = "New"
    override val condGood = "Good"
    override val condFair = "Fair"
    override val condPoor = "Poor"
    
    // Categories
    override val catAll = "All"
    override val catMedical = "Medical"
    override val catElectronics = "Electronics"
    override val catFlag = "Flag"
    override val catFood = "Food"
    override val catOther = "Other"
    
    // AI Assistant
    override val aiInventoryAssistant = "AI Inventory Assistant"
    override val aiAnalyzeStock = "Analyze Stock"
    override val aiAnalyzeStockDesc = "Analyze current inventory stock conditions and provide recommendations"
    override val aiSuggestProcurement = "Suggest Procurement"
    override val aiSuggestProcurementDesc = "Get suggestions on what items need to be procured based on data"
    override val aiBorrowingReport = "Borrowing Report"
    override val aiBorrowingReportDesc = "Summary and analysis of item borrowing patterns"
    override val aiOverdueAction = "Overdue Action"
    override val aiOverdueActionDesc = "Suggested actions for items that are late being returned"
    override val aiCustomQuery = "Custom Query"
    override val aiCustomQueryDesc = "Ask anything about your inventory"
    override val aiCustomQueryHint = "Example: What items are borrowed most often? What are the suggestions for improving management?"
    override val processing = "Processing..."
    override val runAnalysis = "Run Analysis"
    override val analysisResult = "Analysis Result"
    override val aiEmptyState = "Select an action above then press\n\"Run Analysis\""
    override val aiSystemContext = "Use English."
    
    // Auth
    override val login = "Login"
    override val selectDivision = "Select Division"
    override val adminAccess = "ADMIN ACCESS"
    override val email = "Email"
    override val password = "Password"
    override val forgotPassword = "Forgot Password?"
    override val loginButton = "Login"
    override val dontHaveAccount = "Don't have an account?"
    override val contactAdminForAccount = "Accounts are created by the General Treasurer (Admin). Contact admin to register your division account."
    override val requestAccountFromAdmin = "Request Account from Admin"
    override val welcomeBack = "Welcome Back"
    override val loginSubtitle = "Integrated Inventory Management"
    override val loginOrganization = "HMIF Nexara 2026"

    // Actions & Messages
    override val searchItem = "Search item..."
    override val noItemFound = "No Item Found"
    override val noItemInKategory = "No items in this category yet"
    override val addPhotoTitle = "Item Photo"
    override val addPhotoDescription = "Tap to take photo / choose from gallery"
    override val changePhoto = "Tap to change photo"
    override val deletePhoto = "Delete Photo"
    override val uploadingPhoto = "Uploading photo..."
    override val photoSupportedFormats = "JPG, PNG formats supported"
    override val camera = "Camera"
    override val gallery = "Gallery"
    override val choosePhotoSource = "Choose Photo Source"
    override val choosePhotoSourceDesc = "Take a photo from camera or choose from gallery."
    override val returnProofTitle = "Return Proof"
    override val returnProofDesc = "Take a photo for return proof or choose from gallery."
    override val close = "Close"
    override val adminHead = "Admin / Head"
    override val members = "Members"
    override val noMembers = "No members registered yet."
    override val createAndManageAccountDesc = "Create and manage division member accounts"
    override val resetDataDesc = "Delete all items and borrowing history"
    override val resetDataSuccess = "Data reset successfully"
    override val resetDataError = "Failed to reset data"
    override val darkThemeActive = "On"
    override val darkThemeInactive = "Off"
    override val settings = "Settings"
    override val profileUpdated = "Profile updated"
    override val profilePhotoUpdated = "Profile photo updated"
}
