package com.example.inventra.core.localization

object IndonesianStrings : Strings {
    override val appName = "InventRa"
    override val catalog = "Katalog"
    override val history = "Riwayat"
    override val profile = "Profil"
    override val aiAssistant = "Asisten AI"
    override val home = "Beranda"
    
    // Dashboard
    override val dashboardOverview = "Ringkasan Dashboard"
    override val dashboardSubtitle = "Kelola aset dan pelacakan barang dengan efisien."
    override val totalItems = "TOTAL BARANG"
    override val borrowed = "DIPINJAM"
    override val available = "TERSEDIA"
    override val activeBorrowing = "Peminjaman Aktif"
    override val registerNewItem = "Daftar Barang Baru"
    override val registerNewItemDesc = "Tambah stok baru ke dalam database inventaris dengan cepat."
    override val getStarted = "Mulai Sekarang"
    override val borrower = "Peminjam"
    override val dueDate = "Jatuh tempo"
    override val overdueAlert = "peminjaman terlambat!"
    override val takeAction = "Segera tindak lanjuti."
    override val failedToLoadData = "Gagal memuat data"
    
    // Profile Screen
    override val myProfile = "Profil Divisi"
    override val editProfile = "Edit Profil"
    override val fullName = "Divisi"
    override val phoneNumber = "Nomor HP"
    override val cancel = "Batal"
    override val save = "Simpan"
    override val darkMode = "Tema Gelap"
    override val accountManagement = "Manajemen Akun"
    override val resetAllData = "Reset Semua Data"
    override val logout = "Keluar Akun"
    override val language = "Bahasa"
    override val changeLanguage = "Ganti Bahasa"
    override val confirmResetTitle = "Reset Semua Data"
    override val confirmResetMessage = "Yakin hapus semua item & riwayat peminjaman? Tidak bisa dibatalkan."
    
    // History / Borrowing
    override val borrowing = "Peminjaman"
    override val pending = "Menunggu"
    override val active = "Aktif"
    override val all = "Semua"
    override val returned = "SELESAI"
    override val overdue = "TERLAMBAT"
    override val waitingApproval = "MENUNGGU"
    override val approveBorrow = "Setujui Pinjam"
    override val approveReturn = "Konfirmasi Kembali"
    override val returnItem = "Kembalikan"
    override val returnDate = "Tanggal Kembali"
    override val fine = "Denda"
    override val noHistoryTitle = "Belum Ada Riwayat"
    override val noHistoryDesc = "Belum ada transaksi peminjaman yang tercatat."
    override val noPendingTitle = "Tidak Ada Data"
    override val noPendingDesc = "Tidak ada permintaan pending saat ini."
    override val noActiveTitle = "Tidak Ada Data"
    override val noActiveDesc = "Tidak ada peminjaman aktif saat ini."
    override val pendingActionDesc = "permintaan/pengembalian menunggu persetujuan Admin."
    
    // Items & Detail
    override val itemName = "Nama Barang"
    override val description = "Deskripsi"
    override val location = "Lokasi"
    override val totalStock = "Total Stok"
    override val availableStock = "Tersedia"
    override val category = "Kategori"
    override val condition = "Kondisi"
    override val pic = "Penanggung Jawab"
    override val picPhone = "No. HP Penanggung Jawab"
    override val itemInformation = "Informasi Barang"
    override val loanPolicy = "Kebijakan Peminjaman"
    override val maxDuration = "Durasi Maksimal"
    override val overdueFine = "Denda Keterlambatan"
    override val admin = "Admin"
    override val itemNotFound = "Barang tidak ditemukan"
    override val contactPIC = "Hubungi Penanggung Jawab"
    override val borrow = "Pinjam"
    override val outOfStock = "Habis"
    override val deleteItem = "Hapus Barang"
    override val deleteItemConfirm = "Yakin ingin menghapus barang ini? Tindakan tidak dapat dibatalkan."
    override val requestBorrow = "Ajukan Peminjaman"
    override val requestBorrowDesc = "Permintaan akan diproses oleh Admin."
    override val borrowerNameLabel = "Nama Kepala Divisi *"
    override val submitRequest = "Ajukan"
    override val requestSent = "✅ Permintaan peminjaman terkirim! Tunggu konfirmasi admin."
    override val locationNotSet = "Lokasi tidak diset"

    // Item Conditions
    override val condNew = "Baru"
    override val condGood = "Bagus"
    override val condFair = "Cukup Bagus"
    override val condPoor = "Buruk"
    
    // Categories
    override val catAll = "Semua"
    override val catMedical = "Medis"
    override val catElectronics = "Elektronik"
    override val catFlag = "Bendera"
    override val catFood = "Konsumsi"
    override val catOther = "Lainnya"
    
    // AI Assistant
    override val aiInventoryAssistant = "AI Inventaris Asisten"
    override val aiAnalyzeStock = "Analisis Stok"
    override val aiAnalyzeStockDesc = "Analisis kondisi stok inventaris saat ini dan berikan rekomendasi"
    override val aiSuggestProcurement = "Saran Pengadaan"
    override val aiSuggestProcurementDesc = "Dapatkan saran barang apa yang perlu diadakan berdasarkan data"
    override val aiBorrowingReport = "Laporan Peminjaman"
    override val aiBorrowingReportDesc = "Ringkasan dan analisis pola peminjaman barang"
    override val aiOverdueAction = "Tindak Overdue"
    override val aiOverdueActionDesc = "Saran tindakan untuk barang yang terlambat dikembalikan"
    override val aiCustomQuery = "Tanya Bebas"
    override val aiCustomQueryDesc = "Tanyakan apapun tentang inventaris Anda"
    override val aiCustomQueryHint = "Contoh: Barang apa yang paling sering dipinjam? Apa saran untuk meningkatkan pengelolaan?"
    override val processing = "Memproses..."
    override val runAnalysis = "Jalankan Analisis"
    override val analysisResult = "Hasil Analisis"
    override val aiEmptyState = "Pilih aksi di atas lalu tekan\n\"Jalankan Analisis\""
    override val aiSystemContext = "Gunakan Bahasa Indonesia."
    
    // Auth
    override val login = "Masuk"
    override val selectDivision = "Pilih Divisi"
    override val adminAccess = "AKSES ADMIN"
    override val email = "Email"
    override val password = "Password"
    override val forgotPassword = "Lupa Password?"
    override val loginButton = "Masuk"
    override val dontHaveAccount = "Belum punya akun?"
    override val contactAdminForAccount = "Akun dibuat oleh Bendahara Umum (Admin). Hubungi admin untuk mendaftarkan akun divisi Anda."
    override val requestAccountFromAdmin = "Minta Akun ke Admin"
    override val welcomeBack = "Selamat Datang"
    override val loginSubtitle = "Integrated Inventory Management"
    override val loginOrganization = "HMIF Nexara 2026"

    // Actions & Messages
    override val searchItem = "Cari barang..."
    override val noItemFound = "Tidak Ada Barang"
    override val noItemInKategory = "Belum ada barang dalam kategori ini"
    override val addPhotoTitle = "Foto Barang"
    override val addPhotoDescription = "Ketuk untuk ambil foto / pilih dari galeri"
    override val changePhoto = "Ketuk untuk ganti foto"
    override val deletePhoto = "Hapus Foto"
    override val uploadingPhoto = "Mengunggah foto..."
    override val photoSupportedFormats = "Format JPG, PNG didukung"
    override val camera = "Kamera"
    override val gallery = "Galeri"
    override val choosePhotoSource = "Pilih Sumber Foto"
    override val choosePhotoSourceDesc = "Ambil foto dari kamera atau pilih dari galeri."
    override val returnProofTitle = "Bukti Pengembalian"
    override val returnProofDesc = "Ambil foto bukti pengembalian atau pilih dari galeri."
    override val close = "Tutup"
    override val adminHead = "Kepala Divisi"
    override val members = "Staff"
    override val noMembers = "Belum ada anggota terdaftar."
    override val createAndManageAccountDesc = "Buat dan kelola akun anggota divisi"
    override val resetDataDesc = "Hapus seluruh item dan riwayat peminjaman"
    override val resetDataSuccess = "Data berhasil direset"
    override val resetDataError = "Gagal reset data"
    override val darkThemeActive = "Aktif"
    override val darkThemeInactive = "Nonaktif"
    override val settings = "Pengaturan"
    override val profileUpdated = "Profil diperbarui"
    override val profilePhotoUpdated = "Foto profil diperbarui"
}
