name: Android CI

on:
  push:
    branches: [ "project/123140152-123140162-Gameco" ]
  pull_request:
    branches: [ "project/123140152-123140162-Gameco" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create local.properties
      run: |
        echo "GAMEBRAIN_API_KEY=${{ secrets.GAMEBRAIN_API_KEY }}" >> local.properties
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> local.properties

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: composeApp/build/outputs/apk/debug/*.apk
